export const LOAD_POSTS = "LOAD_POSTS";
export const ADD_POSTS = "ADD_POSTS";
export const DELETE_ALL_POSTS = "DELETE_ALL_POSTS";
export const DELETE_ONE_POSTS = "DELETE_ONE_POSTS";
export const EDIT_POST = "EDIT_POST";

export const ADD_NEW_RESULT_COMMAND_SCOOTER = "ADD_NEW_RESULT_COMMAND_SCOOTER";
export const DELETE_ALL_RESULT_COMMAND_SCOOTER =
  "DELETE_ALL_RESULT_COMMAND_SCOOTER";

export const CHANGE_VALUE_INPUT_ADD_NUMBER_OPEN =
  "CHANGE_VALUE_INPUT_ADD_NUMBER_OPEN";
export const CHANGE_VALUE_INPUT_ADD_NUMBER_OPEN_REMONT =
  "CHANGE_VALUE_INPUT_ADD_NUMBER_OPEN_REMONT";

export const CHANGE_VALUE_IS_ERROR_EXIST_REDUSER =
  "CHANGE_VALUE_IS_ERROR_EXIST_REDUSER";
export const CHANGE_VALUE_IS_ERROR_EXIST_REDUSER_ZERO =
  "CHANGE_VALUE_IS_ERROR_EXIST_REDUSER_ZERO";
